# Generated by Django 4.2.8 on 2023-12-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parts',
            new_name='Part',
        ),
    ]
